version: '3'
services:

  application:
    build: .
    image: zup-academy-metrics
    ports:
      - 8080:8080

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    links:
      - application
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
